[package]
authors = ["Ramsay Leung <ramsayleung@gmail.com>"]
name = "rspotify"
version = "0.8.0"
license = "MIT"
readme = "README.md"
description="Spotify API wrapper"
homepage="https://github.com/samrayleung/rspotify"
repository="https://github.com/samrayleung/rspotify"
keywords=["spotify","api"]
edition = "2018"
[dependencies]
base64 = "0.10.0"
derive_builder = "0.7"
dotenv = "0.13.0"
env_logger = "0.6.0"
itertools = "0.8.0"
log = "0.4"
percent-encoding = "1.0.1"
rand = "0.6.5"
random = "0.12.2"
reqwest ={ version = "0.10.1", features=["json","blocking","socks"]}
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.6.0"
webbrowser = "0.5.0"
lazy_static = "1.0"
failure = "0.1"

[dependencies.chrono]
features = ["serde", "rustc-serialize"]
version = "0.4"

[dev-dependencies]
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"

[features]
blocking = []

[[example]]
name = "device"
required-features = ["blocking"]
path = "examples/blocking/device.rs"

[[example]]
name = "artist_top_tracks"
required-features = ["blocking"]
path = "examples/blocking/artist_top_tracks.rs"

[[example]]
name = "categories"
required-features = ["blocking"]
path = "examples/blocking/categories.rs"