[package]
authors = ["Ramsay Leung <ramsayleung@gmail.com>"]
name = "rspotify"
version = "0.10.0"
license = "MIT"
readme = "README.md"
description="Spotify API wrapper"
homepage="https://github.com/samrayleung/rspotify"
repository="https://github.com/samrayleung/rspotify"
keywords=["spotify","api"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.13", features = ["serde", "rustc-serialize"] }
dotenv = "0.15.0"
failure = "0.1.8"
lazy_static = "1.4.0"
log = "0.4.11"
percent-encoding = "2.1.0"
rand = "0.7.3"
reqwest = { version = "0.10.7", features = ["json", "socks"], default-features = false }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
webbrowser = "0.5.5"

[dev-dependencies]
async_once = { version = "0.1.0", features = ["tokio"] }
tokio = { version = "0.2.22", features = ["full"] }
futures = "0.3.5"

[features]
default = ["reqwest/default-tls"]
blocking = ["reqwest/default-tls", "reqwest/blocking"]
# Passing the TLS features to reqwest.
native-tls = ["reqwest/native-tls"]
native-tls-blocking = ["reqwest/native-tls", "reqwest/blocking"]
native-tls-vendored = ["reqwest/native-tls-vendored"]
native-tls-vendored-blocking = ["reqwest/native-tls-vendored", "reqwest/blocking"]
rustls-tls = ["reqwest/rustls-tls"]
rustls-tls-blocking = ["reqwest/rustls-tls", "reqwest/blocking"]

[[example]]
name = "device"
required-features = ["blocking"]
path = "examples/blocking/device.rs"

[[example]]
name = "me"
required-features = ["blocking"]
path = "examples/blocking/me.rs"

[[example]]
name = "blocking_search"
required-features = ["blocking"]
path = "examples/blocking/search.rs"
            
[[example]]
name = "seek_track"
required-features = ["blocking"]
path = "examples/blocking/seek_track.rs"
