[package]
name = "rspotify"
version = "0.10.0"
authors = ["Ramsay Leung <ramsayleung@gmail.com>"]
license = "MIT"
readme = "README.md"
description = "Spotify API wrapper"
homepage = "https://github.com/ramsayleung/rspotify"
repository = "https://github.com/ramsayleung/rspotify"
keywords = ["spotify","api"]
edition = "2018"

[workspaces]
members = ["crates/*"]

[dependencies]
rspotify_client = { path = "crates/rspotify_client", version = "0.10.0" }
rspotify_http = { path = "crates/rspotify_http", version = "0.10.0" }
rspotify_macros = { path = "crates/rspotify_macros", version = "0.10.0" }
rspotify_model = { path = "crates/rspotify_model", version = "0.10.0" }
rspotify_oauth = { path = "crates/rspotify_oauth", version = "0.10.0" }

chrono = { version = "0.4.13", features = ["serde", "rustc-serialize"] }
derive_builder = "0.9.0"
dotenv = { version = "0.15.0", optional = true }
getrandom = "0.2.0"
log = "0.4.11"
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
thiserror = "1.0.20"
url = "2.1.1"
webbrowser = { version = "0.5.5", optional = true }
strum = { version = "0.20", features = ["derive"] }

[dev-dependencies]
env_logger = "0.8.1"
tokio = { version = "1.0", features = ["rt-multi-thread", "macros"] }
futures = "0.3.5"

[features]
default = ["client-reqwest", "reqwest-default-tls"]
cli = ["webbrowser"]
env-file = ["dotenv"]

# Available clients. By default they don't include a TLS so that it can be
# configured.
client-ureq = ["rspotify_http/client-ureq"]
client-reqwest = ["rspotify_http/client-reqwest"]

# Passing the TLS features to reqwest.
reqwest-default-tls = ["rspotify_http/reqwest-default-tls"]
reqwest-rustls-tls = ["rspotify_http/reqwest-rustls-tls"]
reqwest-native-tls = ["rspotify_http/reqwest-native-tls"]
reqwest-native-tls-vendored = ["rspotify_http/reqwest-native-tls-vendored"]
# Same for ureq.
ureq-rustls-tls = ["rspotify_http/ureq-rustls-tls"]

[package.metadata.docs.rs]
# Also documenting the CLI methods
features = ["cli"]

[[example]]
name = "album"
required-features = ["env-file", "cli", "client-reqwest"]
path = "examples/album.rs"

[[example]]
name = "current_user_recently_played"
required-features = ["env-file", "cli", "client-reqwest"]
path = "examples/current_user_recently_played.rs"

[[example]]
name = "oauth_tokens"
required-features = ["env-file", "cli", "client-reqwest"]
path = "examples/oauth_tokens.rs"

[[example]]
name = "track"
required-features = ["env-file", "cli", "client-reqwest"]
path = "examples/track.rs"

[[example]]
name = "tracks"
required-features = ["env-file", "cli", "client-reqwest"]
path = "examples/tracks.rs"

[[example]]
name = "with_refresh_token"
required-features = ["env-file", "cli", "client-reqwest"]
path = "examples/with_refresh_token.rs"

[[example]]
name = "device"
required-features = ["env-file", "cli", "client-ureq"]
path = "examples/ureq/device.rs"

[[example]]
name = "me"
required-features = ["env-file", "cli", "client-ureq"]
path = "examples/ureq/me.rs"

[[example]]
name = "search"
required-features = ["env-file", "cli", "client-ureq"]
path = "examples/ureq/search.rs"
            
[[example]]
name = "seek_track"
required-features = ["env-file", "cli", "client-ureq"]
path = "examples/ureq/seek_track.rs"
