[package]
authors = ["Ramsay Leung <ramsayleung@gmail.com>"]
name = "rspotify"
version = "0.10.0"
license = "MIT"
readme = "README.md"
description = "Spotify API wrapper"
homepage = "https://github.com/ramsayleung/rspotify"
repository = "https://github.com/ramsayleung/rspotify"
keywords = ["spotify","api"]
edition = "2018"

[dependencies]
# Temporary until https://github.com/rust-lang/rfcs/issues/2739, for
# `maybe_async`.
async-trait = "0.1.40"
base64 = "0.12.3"
chrono = { version = "0.4.13", features = ["serde", "rustc-serialize"] }
derive_builder = "0.9.0"
dotenv = { version = "0.15.0", optional = true }
lazy_static = "1.4.0"
log = "0.4.11"
maybe-async = "0.2.0"
percent-encoding = "2.1.0"
getrandom = "0.2.0"
reqwest = { version = "0.10.7", features = ["json", "socks"], default-features = false, optional = true }
serde = { version = "1.0.115", features = ["derive"] }
serde_json = "1.0.57"
ureq = { version = "1.4.1", features = ["json"], optional = true }
webbrowser = { version = "0.5.5", optional = true }
thiserror = "1.0.20"

[dev-dependencies]
async_once = { version = "0.1.0", features = ["tokio"] }
env_logger = "0.7.1"
tokio = { version = "0.2.22", features = ["full"] }
futures = "0.3.5"

[features]
# default = ["client-reqwest", "reqwest/default-tls"]
default = ["client-ureq"]
cli = ["webbrowser"]
env-file = ["dotenv"]

# Available clients
client-ureq = ["ureq", "maybe-async/is_sync"]
client-reqwest = ["reqwest"]

# Passing the TLS features to reqwest.
reqwest-native-tls = ["reqwest/native-tls"]
reqwest-native-tls-blocking = ["reqwest/native-tls", "reqwest/blocking"]
reqwest-native-tls-vendored = ["reqwest/native-tls-vendored"]
reqwest-native-tls-vendored-blocking = ["reqwest/native-tls-vendored", "reqwest/blocking"]
reqwest-rustls-tls = ["reqwest/rustls-tls"]
reqwest-rustls-tls-blocking = ["reqwest/rustls-tls", "reqwest/blocking"]

[[example]]
name = "album"
required-features = ["env-file", "cli"]
path = "examples/album.rs"

[[example]]
name = "current_user_recently_played"
required-features = ["env-file", "cli"]
path = "examples/current_user_recently_played.rs"

[[example]]
name = "track"
required-features = ["env-file", "cli"]
path = "examples/track.rs"

[[example]]
name = "tracks"
required-features = ["env-file", "cli"]
path = "examples/tracks.rs"

[[example]]
name = "with_refresh_token"
required-features = ["env-file", "cli"]
path = "examples/with_refresh_token.rs"

[[example]]
name = "device"
required-features = ["env-file", "cli", "client-ureq"]
path = "examples/blocking/device.rs"

[[example]]
name = "me"
required-features = ["env-file", "cli", "client-ureq"]
path = "examples/blocking/me.rs"

[[example]]
name = "search"
required-features = ["env-file", "cli", "client-ureq"]
path = "examples/blocking/search.rs"
            
[[example]]
name = "seek_track"
required-features = ["env-file", "cli", "client-ureq"]
path = "examples/blocking/seek_track.rs"
