[package]
authors = ["wb-lzr345319 <wb-lzr345319@alibaba-inc.com>"]
name = "rspotify"
version = "0.1.0"

[dependencies]
base64 = "~0.6.0"
derive_builder = "0.5.1"
dotenv = "0.10.1"
env_logger = "0.5.3"
error-chain = "0.11.0"
hyper = "0.11"
log = "0.4"
percent-encoding = "1.0.1"
rand = "0.4.2"
random = "0.12.2"
reqwest = "0.8.2"
rocket = "0.3.6"
rocket_codegen = "0.3.6"
rocket_contrib = "0.3.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.6.0"
webbrowser = "0.2.2"

[dependencies.chrono]
features = ["serde", "rustc-serialize"]
version = "0.4"
