[package]
name = "webapp"
version = "0.1.0"
authors = ["Ramsay <ramsayleung@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
rocket_contrib = {version = "0.4.5", features= ["handlebars_templates", "tera_templates", "json"]}
rspotify = {version = "0.10.0", features = ["blocking"]}
